### ISSUE TITLE
Whetting Your Appetite for Python Notebook Problem

### ISSUE THREAD

**Issue by julienchastang** [Unidata/online-python-training#116]
```python
TypeError: Cannot cast array data from dtype('<U1') to dtype('float64') according to the rule 'safe'
```
when executing final cell.

**Comment by jrleeman** [comment]
`ax.add_feature(cfeat.BORDERS, linewidth='2', edgecolor='black')`

Should be

`ax.add_feature(cfeat.BORDERS, linewidth=2, edgecolor='black')`

**Comment by julienchastang** [comment]
ping @brianmapes

**Comment by brianmapes** [comment]
ping back

On Jun 26, 2018, at 1:25 PM, Julien Chastang <notifications@github.com<mailto:notifications@github.com>> wrote:


ping @brianmapes<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbrianmapes&data=02%7C01%7Cbmapes%40rsmas.miami.edu%7C4e5d393a80524dc4319d08d5db9aa668%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C636656379617911317&sdata=G9e5%2BOQXr2g6yGv%2BqD7UpZjfefA5qDAlG0f9jkdGoWE%3D&reserved=0>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FUnidata%2Fonline-python-training%2Fissues%2F116%23issuecomment-400433464&data=02%7C01%7Cbmapes%40rsmas.miami.edu%7C4e5d393a80524dc4319d08d5db9aa668%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C636656379617911317&sdata=AFTk0XSaH5%2B6yLJjSXT8Atu4w1g8ND2qO8sjw9CKeH8%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAB_VQuAQxtM4YDYkddlIy5fIl9_LDw_Rks5uAorHgaJpZM4QXAOI&data=02%7C01%7Cbmapes%40rsmas.miami.edu%7C4e5d393a80524dc4319d08d5db9aa668%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C636656379617911317&sdata=YqktWRWh6EWcWcMR3XLtRKW%2B%2Fiii6p9PtAfRo8lqvzk%3D&reserved=0>.

*********************************************
Brian Mapes, Professor
Department of Atmospheric Sciences
Meteorology and Physical Oceanography Program
RSMAS, University of Miami
4600 Rickenbacker Causeway
Miami, FL 33149-1098

phone: (305) 421-4275
fax: (305) 421-4696
email: mapes@miami.edu<mailto:mapes@miami.edu>
Web: http://www.rsmas.miami.edu/users/bmapes/
**********************************************

**Comment by julienchastang** [comment]
@brianmapes This notebook should be working again (#118). You will have to update your repository to see it work on your end. Contact us if you need help with that.
