### ISSUE TITLE
Windows-centric clone github repository instructions

### ISSUE THREAD

**Issue by julienchastang** [Unidata/online-python-training#34]
As far as I can tell, the git/github instructions we have thus far are Mac OS X centric. It would be good to find git/github resources that cover MS Windows, as well.

**Comment by dopplershift** [comment]
Can you elaborate on what resources exactly you find only to be applicable to OSX?

As far as I can see, the only resources that show OSX are the screencasts; however, they're interacting with the GitHub website, which should be completely platform agnostic. The other resources (from GitHub itself) are also web-only, and as far as I can tell don't actually show any os-specific stuff.

**Comment by julienchastang** [comment]
My use case is simply:

I am a Windows user, and I want to clone a repository onto my Desktop. How do I do that?

There are OS X based instructions (https://egghead.io/lessons/javascript-how-to-fork-and-clone-a-github-repository), but none for Windows as far as I see. And late adopters tend to be Windows ppl; part of our target audience.

**Comment by dopplershift** [comment]
Ah, yes, that is a problem--most of the rest of the stuff should still suffice, we just need to cover that one hole it seems.

**Comment by brianmapes** [comment]
OSX has a github desktop client too, maybe that approach can be treated in common with Windows?
- a lurker with poor memory for even the ~5 git command line commands…

On Apr 27, 2016, at 12:46 PM, Julien Chastang <notifications@github.com<mailto:notifications@github.com>> wrote:

My use case is simply:

I am a Windows user, and I want to clone a repository onto my Desktop. How do I do that?

There are OS X based instructions (https://egghead.io/lessons/javascript-how-to-fork-and-clone-a-github-repositoryhttps://urldefense.proofpoint.com/v2/url?u=https-3A__egghead.io_lessons_javascript-2Dhow-2Dto-2Dfork-2Dand-2Dclone-2Da-2Dgithub-2Drepository&d=CwMCaQ&c=y2w-uYmhgFWijp_IQN0DhA&r=6e7NDZhC34cc1mCaueSQWw&m=NJMe59jpV8haFJVZi1uk-p-ysP-bpMh1XgrGfuekw-U&s=T2Gz9l5KYwLA-FCUBY6e9TSwrWlqI9hjPbFybFDR0BU&e=), but none for Windows as far as I see. And late adopters tend to be Windows ppl; part of our target audience.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHubhttps://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Unidata_online-2Dpython-2Dtraining_issues_34-23issuecomment-2D215143832&d=CwMCaQ&c=y2w-uYmhgFWijp_IQN0DhA&r=6e7NDZhC34cc1mCaueSQWw&m=NJMe59jpV8haFJVZi1uk-p-ysP-bpMh1XgrGfuekw-U&s=yX7QjroJ6f51iAZqUgVR5VmVJhNbkkH-NQ_fHs4UgVc&e=

---

Brian Mapes,

**Comment by dopplershift** [comment]
There do seem to be some videos for the GUI client, so that may be an option. I despise that thing though, so I'm not in a good position to evaluate (I'm too much of a git CLI ninja at this point).
